name: Clang Format

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: format1
        run: pwd
      - name: format2
        run: ls -la
      - name: format3
        run: clang-format --style=llvm --sort-includes Source/**/*.cpp Source/**/*.hpp --Werror -i