name: Clang Format

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: format
        run: clang-format --style=llvm --sort-includes Source/**/*.cpp Source/**/*.hpp --Werror -i